
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebdeployment
  labels:
    app: Shruti_01
spec:
  replicas: 6
  selector:
    matchLabels:
      app: Shruti_01
  template:
    metadata:
      labels:
        app: Shruti_01
    spec:
      containers:
      - name: Shruti_01
        image: shruti201/tomcat
        ports:
        - containerPort: 8080
